version: "3.1"
services:

  mysql:
    image: mysql:5.7
    networks:
      - calculator-net
    volumes:
      - ./db/:/var/lib/mysql
    environment:
    #!!unsafe!!
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  php:
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    ports:
      - 9000
    networks:
      - calculator-net
    depends_on:
     - mysql
    volumes:
      - ./calculator:/usr/share/nginx/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini
      - ./logs/php/:/var/log/php

  php-composer:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: dockerfiles/php.composer/Dockerfile
    volumes:
      - ./calculator:/usr/share/nginx/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini
      - ./logs/php/:/var/log/php
    tty: true

  php-migrator:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: dockerfiles/php.migrator/Dockerfile
    volumes:
      - ./calculator:/usr/share/nginx/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini
      - ./logs/php/:/var/log/php

  nginx:
    image: nginx:alpine
    networks:
      - calculator-net
    ports:
      - 8512:80
    depends_on:
      - php
    volumes:
      - ./config/nginx-vhost.conf:/etc/nginx/conf.d/default.conf
      - ./calculator/:/usr/share/nginx/html
      - ./logs/nginx/:/var/log/nginx

networks:
  calculator-net: